### ISSUE TITLE
Код нейросети

### ISSUE THREAD

**Issue by bekh6ex** [LanaLob/algorithm_sveta#1]
Я посмотрел вашу презентацию результата на хакатоне и был очень впечатлён!
Мне захотелось разобраться как вы это сделали, но я не нашёл кода нейросети и данных.
Вы их планируете выложить?

**Comment by uniconstructor** [comment]
@bekh6ex насколько я понял - нужно смотреть раздел №4 "Обучение нейросети" в readme: https://github.com/LanaLob/algorithm_sveta#4-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9

Сам код обучения (как и указано в readme) лежит в файле: https://github.com/LanaLob/algorithm_sveta/blob/main/Analysis_Models.ipynb

Я тоже сначала подумал что сами модели доступны только в сериализованном виде (pickle), но если внимательно посмотреть код - то видно что этот файл как раз и создает pickle-дампы нейронок а не загружает уже созданные, так что похожо что это он и есть.

Если стоит цель разобраться в том как все работает - то можно начать с изучения градиентного бустинга на котором это построено, вот тут довольно неплохой гайд: https://www.analyticsvidhya.com/blog/2021/09/gradient-boosting-algorithm-a-complete-guide-for-beginners/

**Comment by bekh6ex** [comment]
Спасибо.
Просто ничего этого тут не было когда я это писал.
